import Link from "next/link";
import { bookingTransitionPath } from "./lib/booking";

export default function Home(){return <>
<section className="hero"><img className="hero-image" src="/images/hero.webp" alt="Thoddoo Sun Sky Inn island surroundings" width={1800} height={1013} loading="eager" decoding="async" fetchPriority="high"/><div className="hero-shade"/><div className="shell hero-copy"><span className="eyebrow light">Boutique island stay · Thoddoo, Maldives</span><h1>Wake up to island life.</h1><p>A welcoming nine-room guesthouse where warm Maldivian hospitality, tropical mornings and unforgettable ocean experiences come together.</p><div className="actions"><a className="btn btn-gold" href={bookingTransitionPath}>Check availability</a><Link className="btn btn-glass" href="/stay">Explore your stay</Link></div></div></section>
<section className="quick-strip"><div><b>From USD 85</b><span>per room</span></div><div><b>Breakfast included</b><span>fresh island mornings</span></div><div><b>Direct support</b><span>WhatsApp concierge</span></div><div><b>9 rooms</b><span>personal hospitality</span></div></section>
<section className="section shell split"><div><span className="eyebrow">Stay close to everything</span><h2>A calm base for discovering Thoddoo</h2><p>Rest in bright, comfortable rooms, enjoy breakfast in the garden and let our local team arrange transfers and island adventures.</p><Link className="text-link" href="/stay">Discover the rooms →</Link></div><img className="rounded" src="/images/room-hero.webp" alt="Deluxe room" width={1400} height={933} loading="lazy" decoding="async"/></section>
<section className="section section-cream"><div className="shell"><div className="section-head"><div><span className="eyebrow">Curated for your holiday</span><h2>Signature experiences</h2></div><Link className="text-link" href="/experiences">Explore all experiences →</Link></div><div className="card-grid three"><article className="image-card"><img src="/images/sandbank.webp" alt="Half Day Trip" width={1200} height={1600} loading="lazy" decoding="async"/><div><h3>Half Day Trip</h3><p>A compact island-and-sea outing arranged for Sun Sky Inn guests.</p></div></article><article className="image-card"><img src="/images/lagoon.webp" alt="Manta Snorkeling" width={1400} height={788} loading="lazy" decoding="async"/><div><h3>Manta Snorkeling</h3><p>A memorable marine-life experience arranged around local conditions.</p></div></article><article className="image-card"><img src="/images/island.webp" alt="Sandbank Trip" width={1400} height={788} loading="lazy" decoding="async"/><div><h3>Sandbank Trip</h3><p>Scenic time on a sandbank with details confirmed by our team.</p></div></article><article className="image-card"><img src="/images/lagoon.webp" alt="Dolphin Cruise" width={1400} height={788} loading="lazy" decoding="async"/><div><h3>Dolphin Cruise</h3><p>A relaxed ocean cruise ideal for golden-hour island evenings.</p></div></article></div></div></section>
<section className="section shell cta"><span className="eyebrow light">Book with confidence</span><h2>Your Thoddoo story starts here.</h2><p>Reserve directly or speak with our team for rooms, transfers and experiences.</p><div className="actions"><a className="btn btn-gold" href={bookingTransitionPath}>Book direct</a><a className="btn btn-glass" href="https://wa.me/9609910136">WhatsApp us</a></div></section>
</>}
